---

- name: Display Ansible Network Information
  connection: local
  hosts: all
  become: yes
  vars:
     my_mood: happy
     var_one: awesome
     var_two: ansible is
     var_three: "{{var_two}} {{var_one}}"
  tasks:
    - name: print variables
      debug: 
          msg: "{{var_three}}"
      when: my_mood == "happy"
