name: opence_env
channels:
  - conda-forge
  - https://ftp.osuosl.org/pub/open-ce/current/
dependencies:
  - python=3.9
  - numba
  - cudatoolkit
  - pycuda
  - cupy
  - cudnn
  - cutensor
  - nccl
  - flask
