ARG UBI_MINIMAL_VERSION="latest"
FROM registry.access.redhat.com/ubi8/ubi:${UBI_MINIMAL_VERSION}
RUN yum update -y
RUN yum -y install python3 python3-pip python3-tkinter -y

RUN pip3 install --upgrade cython \
    && pip3 install --upgrade pip




COPY . .
RUN pip3 install --no-cache-dir -r src/requirements.txt

ENTRYPOINT [ "python3" ]

CMD [ "src/main.py" ]