FROM registry.access.redhat.com/ubi8/python-39

RUN /opt/app-root/bin/python3.9 -m pip install --upgrade pip

COPY . .

RUN pip install --no-cache-dir -r src/requirements.txt

ENTRYPOINT [ "python" ]

CMD [ "src/main.py" ]