FROM ubuntu:latest
LABEL author="Rajeev Kumar Gupta"
LABEL description="An example Containerfile"
RUN sudo apt-get update -y
RUN sudo apt-get install -y python
COPY hello-world.py
CMD python hello-world.py